//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomersTransactions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransaction
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string Transaction { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
